name: Checks
on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install TeX Live
        uses: zauguin/install-texlive@v3
        with:
          package_file: .github/tl_packages

      - name: Run l3build
        run: l3build ctan -q -H

